version: 0.0
os: linux
files:
  - source: CafeCoffeeDay
    destination: /home/ec2-user/CCD-Proj
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh
